# Generated by Django 4.2.7 on 2023-12-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_account', '0002_remove_patient_nin'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemeduser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
