# Generated by Django 4.2.7 on 2023-12-05 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_account', '0003_telemeduser_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='Hospital',
            new_name='hospital',
        ),
    ]
