# Generated by Django 4.2.7 on 2023-12-08 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_account', '0006_alter_doctor_specialty_delete_docspecialty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patient_record',
        ),
    ]
