# Generated by Django 4.2.7 on 2024-04-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "users_account",
            "0008_doctorprofile_patientprofile_remove_patient_patient_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="telemeduser",
            name="date_added",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="telemeduser",
            name="date_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="telemeduser",
            name="first_name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="telemeduser",
            name="is_active",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="telemeduser",
            name="is_admin",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="telemeduser",
            name="is_staff",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="telemeduser",
            name="last_name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="telemeduser",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
