# Generated by Django 4.2.7 on 2023-12-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_condition', models.CharField(max_length=50)),
                ('allergies', models.CharField(blank=True, max_length=70, null=True)),
                ('current_medication', models.CharField(blank=True, max_length=150, null=True)),
                ('lab_test', models.CharField(blank=True, max_length=100, null=True)),
                ('test_result', models.CharField(blank=True, max_length=100, null=True)),
                ('prescription', models.TextField(blank=True, max_length=250, null=True)),
                ('new_appointment', models.DateField()),
                ('note', models.TextField(blank=True, null=True)),
                ('referral', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
