# Generated by Django 4.2.7 on 2023-12-08 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient_record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='record_owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='record_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
